name: Execution Result Validation

on:
  push:
    paths:
      # Only trigger when seed_dataset.json files are modified
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  pull_request:
    paths:
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12.0
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install camel-ai[verifiers]==0.2.43
        pip install Pillow
        pip install antlr4-python3-runtime==4.11
        pip install numpy==1.26.4
        pip install sympy==1.13.3
        pip install uv==0.6.12
        pip install math_verify
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          data/*/seed_dataset.json
          data/games/*/seed_dataset.json

    - name: Run validation for changed files
      run: |
        cd data
        # Loop through all changed files and run validation for each
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing $file"
          python execute_compare_action.py --file_path "$file" > "validation_${file//\//_}.txt" 2>&1
        done

    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: data/validation_*.txt
        retention-days: 14