name: Domain Validation

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12.0
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.0'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install camel-ai[verifiers, embeddings]==0.2.43 antlr4-python3-runtime==4.11
    
    - name: Run validation
      run: |
        cd data
        python execute_compare_action.py