name: Data Schema Validation

on:
  push:
    paths:
      # Only trigger when seed_dataset.json files are modified
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        files: |
          data/*/seed_dataset.json
          data/games/*/seed_dataset.json

    - name: Run schema validation for changed files
      run: |
        cd data
        # Loop through all changed files and run validation for each
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing $file"
          python schema_check.py --file_path "$file"
        done