name: Schema Validation

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    
    - name: Run schema validation
      run: |
        python new_loong/loong/data/schema_check.py
    
    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: validation-results
        path: validation_statistics.json
    
    - name: Check validation results
      run: |
        if [ -f validation_statistics.json ]; then
          if [ "$(jq '.total_missing | length' validation_statistics.json)" -gt 0 ]; then
            echo "Schema validation failed! See validation_statistics.json for details"
            exit 1
          fi
        fi