name: Dataset Size Validation

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'
    
    - name: Run dataset size validation
      run: |
        cd data  # Adjust to correct directory
        python number_check.py