name: Dataset Size Validation

on:
  push:
    branches:
      - main 
    paths:
      # Only trigger when seed_dataset.json files are modified
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  pull_request:
    paths:
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        since_last_remote_commit: true
        files: |
          data/*/seed_dataset.json
          data/games/*/seed_dataset.json

    - name: Run dataset size validation for changed files
      run: |
        cd data
        # Loop through all changed files and run validation for each
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "Processing $file"
          python number_check.py --file_path "$file"
        done