name: Data Schema Validation

on:
  push:
    branches:
      - main 
    paths:
      # Only trigger when seed_dataset.json files are modified
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  pull_request:
    paths:
      - 'data/*/seed_dataset.json'
      - 'data/games/*/seed_dataset.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datasets
        pip install huggingface_hub
        pip install camel-ai[datasets,datahubs]==0.2.45

    - name: Run upload to hf
      run: |
        python scripts/upload_to_hf.py