name: Upload to Hugging Face

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**/*.json'
  
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Increase timeout to 2 hours
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install camel-ai
        pip install huggingface_hub datasets backoff requests

    - name: Upload to HuggingFace
      run: |
        python scripts/upload_to_hf.py
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}